#!/usr/bin/env python3
"""Generate requirements/*.txt from pyproject.toml.

pyproject.toml is the single source of truth for versions; the requirements
files exist only because Docker layer caching wants a small file that changes
rarely. `tests/unit/test_requirements_sync.py` fails if they drift apart, so
run this script after editing dependencies.
"""

from __future__ import annotations

import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]

HEADER = (
    "# GENERATED by scripts/sync_requirements.py from pyproject.toml — do not edit.\n"
    "# Regenerate with: python scripts/sync_requirements.py\n"
)

# torch publishes CUDA wheels on PyPI for linux; we want the CPU build.
TORCH_CPU_INDEX = "--extra-index-url https://download.pytorch.org/whl/cpu\n"


def render() -> dict[str, str]:
    """Return {relative path: file contents} for every requirements file."""
    data = tomllib.loads((ROOT / "pyproject.toml").read_text())
    project = data["project"]
    extras = project["optional-dependencies"]

    files = {
        "requirements/api.txt": (project["dependencies"], True),
        "requirements/corpus.txt": (extras["corpus"], False),
        "requirements/dev.txt": (extras["dev"], False),
        "requirements/eval.txt": (extras["eval"], False),
    }
    out: dict[str, str] = {}
    for path, (deps, needs_torch_index) in files.items():
        body = HEADER
        if needs_torch_index:
            body += TORCH_CPU_INDEX
        body += "".join(f"{dep}\n" for dep in deps)
        out[path] = body
    return out


def main() -> int:
    check = "--check" in sys.argv
    drifted = []
    for path, content in render().items():
        target = ROOT / path
        current = target.read_text() if target.exists() else None
        if current == content:
            continue
        drifted.append(path)
        if not check:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content)
    if check and drifted:
        print("out of sync with pyproject.toml: " + ", ".join(drifted))
        return 1
    if not check:
        print(f"wrote {len(render())} files ({len(drifted)} changed)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
