"""Initial schema: the ten Phase 1.1 tables, pgvector, HNSW and GIN indexes.

Creates the ``vector`` extension, every table from spec §06, and the three
indexes that carry the retrieval load:

* HNSW on ``kb_chunks.embedding`` (cosine, m=16, ef_construction=64);
* GIN on ``kb_chunks.tsv`` for BM25 via ``ts_rank``;
* btree on ``(statute_id, section_no_sort)`` for citation-ordered browsing.

The embedding column is ``vector(768)`` — the dimensionality of
``NyayaLabs98/nyaya-embed-v1`` (docs/adr/0001). The number is written out rather
than imported from ``app.core.config`` so this migration stays a frozen snapshot
of the schema at this revision.

Revision ID: 0001
Revises:
Create Date: 2026-09-10 23:12:49.171393
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from pgvector.sqlalchemy import Vector
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # pgvector must exist before any vector column is created. gen_random_uuid()
    # (used by users and api_credentials) is core PostgreSQL from 13 onward, so
    # pgcrypto is not needed.
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ask_logs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("lang", sa.String(length=8), nullable=False),
        sa.Column("rewritten_question", sa.Text(), nullable=True),
        sa.Column(
            "retrieved_section_ids",
            postgresql.ARRAY(sa.BigInteger()),
            server_default="{}",
            nullable=False,
        ),
        sa.Column("top_score", sa.Float(), nullable=True),
        sa.Column("answered", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("abstained", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("citation_violation", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("model", sa.String(length=120), nullable=True),
        sa.Column("tokens_in", sa.Integer(), nullable=True),
        sa.Column("tokens_out", sa.Integer(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("not (answered and abstained)", name="ck_ask_logs_answer_or_abstain"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_ask_logs_created_at", "ask_logs", ["created_at"], unique=False)
    op.create_index("ix_ask_logs_violation", "ask_logs", ["citation_violation"], unique=False)
    op.create_table(
        "ingest_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_portal", sa.String(length=60), nullable=False),
        sa.Column("statute_slug", sa.String(length=120), nullable=True),
        sa.Column("command", sa.String(length=200), nullable=True),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("docs_fetched", sa.Integer(), server_default="0", nullable=False),
        sa.Column("sections_written", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "warnings", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column(
            "errors", postgresql.JSONB(astext_type=sa.Text()), server_default="[]", nullable=False
        ),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.CheckConstraint(
            "status in ('running', 'succeeded', 'partial', 'failed')", name="ck_ingest_runs_status"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_ingest_runs_slug_started", "ingest_runs", ["statute_slug", "started_at"], unique=False
    )
    op.create_table(
        "statutes",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("slug", sa.String(length=120), nullable=False),
        sa.Column("short_title", sa.String(length=300), nullable=False),
        sa.Column("long_title", sa.Text(), nullable=True),
        sa.Column("act_number", sa.String(length=40), nullable=True),
        sa.Column("year", sa.Integer(), nullable=False),
        sa.Column("enacted_on", sa.Date(), nullable=True),
        sa.Column("jurisdiction", sa.String(length=60), nullable=False),
        sa.Column("level", sa.String(length=10), nullable=False),
        sa.Column("ministry", sa.String(length=200), nullable=True),
        sa.Column("source_portal", sa.String(length=60), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("source_sha256", sa.String(length=64), nullable=False),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("is_repealed", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("repealed_by_id", sa.BigInteger(), nullable=True),
        sa.Column("section_count", sa.Integer(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("level in ('central', 'state')", name="ck_statutes_level"),
        sa.CheckConstraint("char_length(source_sha256) = 64", name="ck_statutes_sha256_len"),
        sa.CheckConstraint("year between 1800 and 2200", name="ck_statutes_year"),
        sa.ForeignKeyConstraint(["repealed_by_id"], ["statutes.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index(
        "ix_statutes_jurisdiction_year", "statutes", ["jurisdiction", "year"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), server_default="true", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("position('@' in email) > 1", name="ck_users_email_shape"),
        sa.CheckConstraint("email = lower(email)", name="ck_users_email_lowercase"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_table(
        "api_credentials",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column("ciphertext", sa.LargeBinary(), nullable=False),
        sa.Column("nonce", sa.LargeBinary(), nullable=False),
        sa.Column("key_version", sa.Integer(), server_default="1", nullable=False),
        sa.Column("key_hint", sa.String(length=8), nullable=True),
        sa.Column("last_verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("key_version >= 1", name="ck_api_credentials_key_version"),
        sa.CheckConstraint("octet_length(ciphertext) > 0", name="ck_api_credentials_cipher"),
        sa.CheckConstraint("octet_length(nonce) = 12", name="ck_api_credentials_nonce_len"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "provider", name="uq_api_credentials_user_provider"),
    )
    op.create_table(
        "statute_parts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("statute_id", sa.BigInteger(), nullable=False),
        sa.Column("parent_id", sa.BigInteger(), nullable=True),
        sa.Column("kind", sa.String(length=10), nullable=False),
        sa.Column("number", sa.String(length=40), nullable=True),
        sa.Column("heading", sa.Text(), nullable=True),
        sa.Column("order_idx", sa.Integer(), nullable=False),
        sa.CheckConstraint("kind in ('part', 'chapter')", name="ck_statute_parts_kind"),
        sa.ForeignKeyConstraint(["parent_id"], ["statute_parts.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["statute_id"], ["statutes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("statute_id", "order_idx", name="uq_statute_parts_order"),
    )
    op.create_index(
        "ix_statute_parts_statute_parent",
        "statute_parts",
        ["statute_id", "parent_id"],
        unique=False,
    )
    op.create_table(
        "statute_sections",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("statute_id", sa.BigInteger(), nullable=False),
        sa.Column("part_id", sa.BigInteger(), nullable=True),
        sa.Column("section_no", sa.String(length=40), nullable=False),
        sa.Column("section_no_sort", sa.String(length=64, collation="C"), nullable=False),
        sa.Column("marginal_note", sa.Text(), nullable=True),
        sa.Column("text_verbatim", sa.Text(), nullable=False),
        sa.Column("text_raw", sa.Text(), nullable=True),
        sa.Column(
            "footnotes",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column("amendment_note", sa.Text(), nullable=True),
        sa.Column("commenced_on", sa.Date(), nullable=True),
        sa.Column("as_of_date", sa.Date(), nullable=False),
        sa.Column("is_omitted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("order_idx", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["part_id"], ["statute_parts.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["statute_id"], ["statutes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("statute_id", "order_idx", name="uq_statute_sections_order"),
        sa.UniqueConstraint("statute_id", "section_no", name="uq_statute_sections_no"),
    )
    op.create_index(
        "ix_statute_sections_citation_order",
        "statute_sections",
        ["statute_id", "section_no_sort"],
        unique=False,
    )
    op.create_index("ix_statute_sections_part", "statute_sections", ["part_id"], unique=False)
    op.create_table(
        "kb_chunks",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("section_id", sa.BigInteger(), nullable=False),
        sa.Column("statute_id", sa.BigInteger(), nullable=False),
        sa.Column("chunk_idx", sa.Integer(), nullable=False),
        sa.Column("heading_prefix", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("embedding", Vector(768), nullable=True),
        sa.Column("tsv", postgresql.TSVECTOR(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("token_count > 0", name="ck_kb_chunks_token_count"),
        sa.ForeignKeyConstraint(["section_id"], ["statute_sections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["statute_id"], ["statutes.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("section_id", "chunk_idx", name="uq_kb_chunks_section_idx"),
    )
    op.create_index("ix_kb_chunks_statute", "kb_chunks", ["statute_id"], unique=False)

    # Dense retrieval. Cosine distance, because the embedding model is trained
    # for it; m and ef_construction are the values from spec §06. The index is
    # created empty here and rebuilt after bulk load in Stage 4.
    op.create_index(
        "ix_kb_chunks_embedding_hnsw",
        "kb_chunks",
        ["embedding"],
        unique=False,
        postgresql_using="hnsw",
        postgresql_with={"m": 16, "ef_construction": 64},
        postgresql_ops={"embedding": "vector_cosine_ops"},
    )
    # Sparse retrieval (BM25 via ts_rank).
    op.create_index(
        "ix_kb_chunks_tsv_gin",
        "kb_chunks",
        ["tsv"],
        unique=False,
        postgresql_using="gin",
    )

    op.create_table(
        "section_explanations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("section_id", sa.BigInteger(), nullable=False),
        sa.Column("explanation_plain", sa.Text(), nullable=False),
        sa.Column("lang", sa.String(length=8), server_default="en", nullable=False),
        sa.Column("model_used", sa.String(length=120), nullable=False),
        sa.Column("prompt_version", sa.String(length=40), nullable=False),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("human_reviewed", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(["section_id"], ["statute_sections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "section_id", "lang", "prompt_version", name="uq_section_explanations_version"
        ),
    )
    op.create_table(
        "statute_links",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("from_section_id", sa.BigInteger(), nullable=False),
        sa.Column("to_section_id", sa.BigInteger(), nullable=False),
        sa.Column("relation", sa.String(length=20), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "relation in ('refers_to', 'amended_by', 'see_also')", name="ck_statute_links_relation"
        ),
        sa.CheckConstraint(
            "from_section_id <> to_section_id", name="ck_statute_links_no_self_reference"
        ),
        sa.ForeignKeyConstraint(["from_section_id"], ["statute_sections.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["to_section_id"], ["statute_sections.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "from_section_id", "to_section_id", "relation", name="uq_statute_links_edge"
        ),
    )
    op.create_index("ix_statute_links_to", "statute_links", ["to_section_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_statute_links_to", table_name="statute_links")
    op.drop_table("statute_links")
    op.drop_table("section_explanations")
    op.drop_index("ix_kb_chunks_tsv_gin", table_name="kb_chunks")
    op.drop_index("ix_kb_chunks_embedding_hnsw", table_name="kb_chunks")
    op.drop_index("ix_kb_chunks_statute", table_name="kb_chunks")
    op.drop_table("kb_chunks")
    op.drop_index("ix_statute_sections_part", table_name="statute_sections")
    op.drop_index("ix_statute_sections_citation_order", table_name="statute_sections")
    op.drop_table("statute_sections")
    op.drop_index("ix_statute_parts_statute_parent", table_name="statute_parts")
    op.drop_table("statute_parts")
    op.drop_table("api_credentials")
    op.drop_table("users")
    op.drop_index("ix_statutes_jurisdiction_year", table_name="statutes")
    op.drop_table("statutes")
    op.drop_index("ix_ingest_runs_slug_started", table_name="ingest_runs")
    op.drop_table("ingest_runs")
    op.drop_index("ix_ask_logs_violation", table_name="ask_logs")
    op.drop_index("ix_ask_logs_created_at", table_name="ask_logs")
    op.drop_table("ask_logs")
    # ### end Alembic commands ###

    # Nothing else in this database uses pgvector, so a downgrade leaves no trace.
    op.execute("DROP EXTENSION IF EXISTS vector")
